[package]
name = "riptorrent"
version = "0.1.0"
authors = ["Jonas Mathisrud Sterud <jonas.sterud@gmail.com>"]
edition = "2021"
description = "BitTorrent client written in Rust"
repository = "https://github.com/jonassterud/riptorrent"
license = "MIT"

[dependencies]
anyhow = { version = "1.0.64" }
clap = { version = "3.2.20", features = ["derive"] }
sha1_smol = { version = "1.0.0" }
arrayref = { version = "0.3.6" }
rand = { version = "0.8.5" }
urlencoding = { version = "2.1.2" }
reqwest = { version = "0.11.12", features = ["blocking"] }